#%RAML 1.0 NamedExample
shipping:
  shipping_address_id: "1122"
  rel_address: "http://alc.mulesoft.com/api/users/user/vip_user_8/address/1122"
payment:
  credit_card_id: "1231"
  rel_card: "http://alc.mulesoft.com/api/users/user/vip_user_8/credit_card/1122"
items:
  - product_id: "121"
    rel_product: "http://alc.mulesoft.com/api/products/product/121"
    quantity: 1
  - product_id: "122"
    rel_product: "http://alc.mulesoft.com/api/products/product/122"
    quantity: 2
