#%RAML 1.0 NamedExample
order_id: "order_22"
order_number: "order_22_worldwide"
tracking_code: "AA8839II989"
eta: "2016/12/31 10:00:00"
shipping:
  shipping_address_id: "1122"
  rel_address: "http://alc.mulesoft.com/api/users/user/vip_user_8/address/1122"
items:
  - product_id: "121"
    rel_product: "http://alc.mulesoft.com/api/products/product/121"
    quantity: 1
  - product_id: "122"
    rel_product: "http://alc.mulesoft.com/api/products/product/122"
    quantity: 2
