#%RAML 1.0 NamedExample
- order_id: "order_22"
  tracking_code: "12310391209318"
  rel_self: "http://alc.mulesoft.com/api/orders/oder/order_22"
  creation_date: "2015/12/31 10:00:00"
  cost:
    price: 12.0
    tax: 1.0
    final_price: 13.0
  shipping:
    shipping_address_id: "1122"
    rel_address: "http://alc.mulesoft.com/api/users/user/vip_user_8/address/1122"
  items:
    - product_id: "121"
      rel_product: "http://alc.mulesoft.com/api/products/product/121"
      quantity: 1
    - product_id: "122"
      rel_product: "http://alc.mulesoft.com/api/products/product/122"
      quantity: 2
- order_id: "order_23"
  tracking_code: "12310391209318"
  rel_self: "http://alc.mulesoft.com/api/orders/oder/order_22"
  creation_date: "2015/12/31 10:00:00"
  cost:
    price: 12.0
    tax: 1.0
    final_price: 13.0
  shipping:
    shipping_address_id: "1122"
    rel_address: "http://alc.mulesoft.com/api/users/user/vip_user_8/address/1122"
  items:
    - product_id: "121"
      rel_product: "http://alc.mulesoft.com/api/products/product/121"
      quantity: 1
    - product_id: "122"
      rel_product: "http://alc.mulesoft.com/api/products/product/122"
      quantity: 2
      