#%RAML 1.0 NamedExample
id: "231231"
name: "Chuck Norris action toy"
full_description: "Chuck norris action toy description"
rel_self: "http://alc.mulesoft.com/api/products/product/1231231"
rating: 1.2
available_stock: 4
unit_price: 19.00
unit_original_price: 19.00
pictures:  
  - "http://img3.wikia.nocookie.net/__cb20080312162141/uncyclopedia/images/d/dc/Chuck-norris-002.jpg"
  - "http://img3.wikia.nocookie.net/__cb20080312162141/uncyclopedia/images/d/dc/Chuck-norris-002.jpg"
  - "http://img3.wikia.nocookie.net/__cb20080312162141/uncyclopedia/images/d/dc/Chuck-norris-002.jpg"