#%RAML 1.0 NamedExample
- id: 1
  name: ELMO
  description: Playskool sesame street play all day Elmo
  productNumber: UUID34234923934293
  manufactured: true
  safetyStockLevel: 540
  standardCost: 78.00
  listPrice: 99.90
  size: 200x300
  sizeUnitMeasureCode: in
  weightUnitMeasureCode: gr
  weight: 400
  daysToManufacture: 10
  categories: 
    - playskool
    - sesame street
  stock: 2800
  colors:
    - blue
    - red
    - green
  images:
    - /wcsstore/HTSStorefrontAssetStore/Attachment/HomePage/Product eSpots/Play-All-Day-Elmo.png
- id: 2
  name: ELMO
  description: Playskool sesame street play all day Elmo
  productNumber: UUID34234923934293
  manufactured: true
  safetyStockLevel: 540
  standardCost: 78.00
  listPrice: 99.90
  size: 200x300
  sizeUnitMeasureCode: in
  weightUnitMeasureCode: gr
  weight: 400
  daysToManufacture: 10
  categories: 
    - playskool
    - sesame street
  stock: 2800
  colors:
    - blue
    - red
    - green
  images:
    - /wcsstore/HTSStorefrontAssetStore/Attachment/HomePage/Product eSpots/Play-All-Day-Elmo.png
