#%RAML 1.0 Library
types:
  product:
    properties:
      id?: string
      name: string
      full_description?: string
      rel_self?: string
      pictures?: string[]
      rating?: number
      available_stock: number
      unit_price?: number
      unit_original_price?: number
