#%RAML 1.0 Library
types:
  user:
    properties:
      id?: string
      username: string
      email: string
      firstname: string
      lastname: string
      password: string
      mobile_number: string
      last_login?: string
