pipeline {
  agent {
    label 'mule-builder' // Name of the configure docker container
  }
  environment { //Global Environments
    DEPLOY_CREDS = credentials('deploy-anypoint-user') //Deployer user
    MULE_VERSION = '4.1.5'
    BG="1Platform\\Public\\Admin"
    WORKER = "MICRO"
    ENVIRONMENT = 'Production'
    APP_NAME = 'public-cicd-apps-cleanup'
  }

  stages {
    stage('Prepare') {//Copy the configuration file according to the environment
      steps {
        configFileProvider([configFile(fileId: "${BRANCH_NAME}-configuration.yaml", replaceTokens: true, targetLocation: './cicd-cleanup/src/main/resources/config/configuration.yaml')]) {
            sh 'echo "Branch NAME: $BRANCH_NAME"'
        }
      }
    }
    stage('Build') {//Build the package
      steps {
        sh 'mvn -B -pl cicd-cleanup clean package -DskipTests'
      }
    }

    stage('Deploy') {//Deploy to Production
        steps {
          sh 'mvn -V -B -DskipTests -pl cicd-cleanup deploy -DmuleDeploy -Dmule.version=$MULE_VERSION -Danypoint.username=$DEPLOY_CREDS_USR -Danypoint.password=$DEPLOY_CREDS_PSW -Dcloudhub.app=$APP_NAME -Dcloudhub.environment=$ENVIRONMENT -Dcloudhub.worker=$WORKER -Dcloudhub.bg="$BG"'
        }
    }
  }

  post {
      always {
       step([$class: 'hudson.plugins.chucknorris.CordellWalkerRecorder'])
      }
  }  

  tools {// Select Tools to use
    maven 'M3'
  }
}
